<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <LSLRuntimeVersion>1.16.2</LSLRuntimeVersion>
  </PropertyGroup>

  <PropertyGroup Label="Build">
    <BuildInParallel>false</BuildInParallel>
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>CS2008</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <ExcludeSymbolsFromPackage>false</ExcludeSymbolsFromPackage>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="/" />
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
