<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RID>win-x64</RID>
    <NativeAssetTitle>liblsl-$(LSLRuntimeVersion)-Win_amd64</NativeAssetTitle>
    <NativeAssetFile>$(NativeAssetTitle).zip</NativeAssetFile>
    <NativeLibBaseDir>bin</NativeLibBaseDir>
    <NativeLibPrefix></NativeLibPrefix>
    <NativeLibExt>dll</NativeLibExt>
  </PropertyGroup>

  <PropertyGroup>
    <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeAdditionalTfmSpecificPackageFiles</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
</Project>
