<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>LSL.Net is a cross-platform C# binding of lab streaming layer</Description>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!--
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <!--
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  -->

  <ItemGroup Label="Package References">
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
